// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the GUI boundary and intentionally does not import daemon code.
 * Wails v3 service: 공개 메서드가 프런트엔드 바인딩으로 노출된다.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(713661858);
}

/**
 * IsTrayVisible 은 WebView가 다시 만들어졌을 때도 네이티브 퀵뷰의 현재 상태를 복구하게 한다.
 * tray:shown/tray:hidden은 상태 변경 알림일 뿐이므로 마운트 시점의 상태 원본이 될 수 없다.
 */
export function IsTrayVisible(): $CancellablePromise<boolean> {
    return $Call.ByID(2463498113);
}

/**
 * OpenMainSettings 는 메인 창을 열고 설정 모달을 띄우라는 이벤트를 보낸다 (퀵뷰 "트레이 설정").
 */
export function OpenMainSettings(): $CancellablePromise<void> {
    return $Call.ByID(975306329);
}

/**
 * OpenMainWindow 는 퀵뷰를 닫고 메인 창을 앞으로 가져온다 (퀵뷰 "Pulsemetry 열기").
 */
export function OpenMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(3129367688);
}

/**
 * Quit 은 앱을 완전히 종료한다 (퀵뷰 전원 버튼).
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(3181047470);
}
