// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the GUI boundary and intentionally does not import daemon code.
 * Wails v3 service: 공개 메서드가 프런트엔드 바인딩으로 노출된다.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(713661858);
}
