// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Dashboard 는 프런트엔드가 부를 수 있는 Go 함수의 목록이다. Wails 가 공개 메서드를
 * 전부 TS 로 뽑으므로, 화면이 실제로 쓰는 것만 여기 둔다.
 * 
 * GUI 는 SQLite 를 열지 않는다. 데몬이 읽어서 내려준 것을 받는다 (internal/localapi).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tray$0 from "../../internal/dashboard/tray/models.js";

/**
 * RefreshTray 는 데몬에 갱신을 명령하고 그 결과를 다시 받는다 (퀵뷰의 수동 새로고침).
 */
export function RefreshTray(q: tray$0.Query): $CancellablePromise<tray$0.Snapshot> {
    return $Call.ByID(1419183219, q);
}

/**
 * Tray 는 트레이 퀵뷰 한 장에 필요한 전부다. 갱신 주기 안이면 캐시를 그대로 준다.
 */
export function Tray(q: tray$0.Query): $CancellablePromise<tray$0.Snapshot> {
    return $Call.ByID(3098134964, q);
}
