// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfo is owned by the GUI process.
 */
export interface AppInfo {
    "name": string;
    "version": string;
}
