// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktopinstall$0 from "../../internal/desktopinstall/models.js";

export function Execute(deleteData: boolean): $CancellablePromise<desktopinstall$0.Result> {
    return $Call.ByID(661795403, deleteData);
}

/**
 * Finish는 성공한 제거 창이 닫힌 뒤에만 자기 파일을 지우도록 작업을 넘긴다.
 */
export function Finish(): $CancellablePromise<void> {
    return $Call.ByID(4245440539);
}

export function Preview(deleteData: boolean): $CancellablePromise<desktopinstall$0.Preview> {
    return $Call.ByID(580057704, deleteData);
}
