// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Snapshot 은 데몬이 소유하고 CLI·GUI가 읽는 업데이트 상태다.
 * UpdateAvailable이 nil이면 아직 성공한 조회가 없다. 시각은 UTC RFC3339이며 미확인은 빈 문자열이다.
 */
export interface Snapshot {
    "status": string;
    "current_version": string;
    "latest_version": string;
    "update_available": boolean | null;
    "last_attempt_at": string;
    "last_success_at": string;
}
