// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vendor$0 from "../vendor/models.js";

/**
 * ExtraAllowance 는 플랜 한도를 넘겨 쓸 수 있는 **추가 한도**다 (Claude 의 extra usage,
 * Codex 의 크레딧).
 * 
 * Supported=false 는 "벤더가 이 계정에 대해 추가 한도를 알려주지 않았다" 는 뜻이고,
 * Supported=true·Enabled=false 는 "알려줬는데 꺼져 있다" 는 뜻이다. 둘을 뭉치면 화면이
 * "추가 한도 없음" 과 "모름" 을 구분하지 못한다.
 */
export interface ExtraAllowance {
    "supported": boolean;
    "enabled": boolean;

    /**
     * UsedRatio 는 추가 한도 자체의 소진율(0.0~1.0)이다. 모르면 0 이다.
     */
    "used_ratio": number;
}

/**
 * PeriodKind 는 한도 창의 종류다. 벤더마다 창을 부르는 이름이 다르므로(Claude 는
 * five_hour·seven_day, Codex 는 window_minutes 정수) 화면이 분기하지 않도록 여기서 통일한다.
 */
export enum PeriodKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PeriodFiveHour = "five_hour",
    PeriodWeekly = "weekly",
    PeriodMonthly = "monthly",

    /**
     * PeriodUnknown 은 우리가 아는 창이 아니라는 뜻이다. 창을 버리지 않고 이 종류로
     * 넘기는 이유는, 벤더가 새 창을 추가했을 때 숫자가 조용히 사라지는 것보다
     * "모르는 창" 으로 보이는 편이 낫기 때문이다. Label 에 원래 이름이 남는다.
     */
    PeriodUnknown = "unknown",
};

/**
 * Reason 은 unavailable 의 기계 판독 가능한 원인이다.
 * 
 * 화면 문구는 이 값에서 파생시키고 Detail 문자열을 파싱하지 않는다. Detail 은 사람이 읽는
 * 보조 설명이며 언제든 바뀔 수 있다. **어느 쪽에도 토큰 조각이 들어가지 않는다.**
 */
export enum Reason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReasonNone = "",

    /**
     * ReasonNotProbed 는 아직 한 번도 조회하지 않았다는 뜻이다. 데몬이 막 떴거나 꺼져
     * 있는 상태이지 사용자가 뭘 잘못한 것이 아니다.
     * 
     * ReasonCredentialMissing 과 반드시 구분해야 한다. 둘을 뭉치면 로그인이 멀쩡한
     * 사용자에게 "로그인하지 않았습니다" 라고 말하게 된다.
     */
    ReasonNotProbed = "not_probed",

    /**
     * ReasonCredentialMissing 은 자격증명 파일이 없다는 뜻이다 — 해당 도구에 로그인하지
     * 않았거나 아예 설치하지 않은, 가장 흔한 정상 상태다.
     */
    ReasonCredentialMissing = "credential_missing",

    /**
     * ReasonCredentialUnreadable 은 파일은 있으나 읽을 권한이 없다는 뜻이다.
     */
    ReasonCredentialUnreadable = "credential_unreadable",

    /**
     * ReasonCredentialMalformed 는 파일을 읽었으나 우리가 아는 모양이 아니라는 뜻이다.
     * 벤더가 자격증명 파일 형식을 바꾸면 여기로 온다.
     */
    ReasonCredentialMalformed = "credential_malformed",

    /**
     * ReasonTokenExpired 는 토큰이 만료됐다는 뜻이다. 파일의 만료 시각으로 미리 알거나
     * 상위가 401·403 으로 거부해서 알게 된다. 우리는 갱신하지 않으므로 벤더 CLI 를 기다린다.
     */
    ReasonTokenExpired = "token_expired",

    /**
     * ReasonNetwork 는 요청이 상대에 닿지 못했다는 뜻이다 (DNS·연결 거부·타임아웃·취소).
     */
    ReasonNetwork = "network_error",

    /**
     * ReasonUpstreamStatus 는 상위가 2xx 가 아닌 응답을 줬다는 뜻이다 (401·403 제외).
     */
    ReasonUpstreamStatus = "upstream_status",

    /**
     * ReasonResponseUnrecognized 는 2xx 를 받았으나 본문이 우리가 아는 모양이 아니라는
     * 뜻이다. **비공개 API 가 바뀌면 여기로 온다** — 이 값이 화면에 늘어나기 시작하면
     * 어댑터를 고쳐야 한다는 신호다.
     */
    ReasonResponseUnrecognized = "response_unrecognized",

    /**
     * ReasonInternal 은 어댑터가 예상 못 한 방식으로 죽었다는 뜻이다. 한 벤더의 버그가
     * 다른 벤더의 숫자까지 지우지 않게 하는 마지막 그물이다.
     */
    ReasonInternal = "internal_error",
};

/**
 * Result 는 벤더 하나의 조회 결과다.
 * 
 * # 여기에 토큰이 들어갈 자리는 없다
 * 
 * 이 구조체는 Wails 바인딩을 통해 그대로 TS 필드가 된다 (ADR 0004). 필드를 추가할 때는
 * "이 값이 화면 스크린샷으로 유출돼도 무해한가" 를 먼저 물어야 한다. 그 물음을 자동화한
 * 것이 leak_test.go 다 — 결과 전체를 리플렉션으로 훑어 토큰 조각이 없음을 단언한다.
 */
export interface Result {
    "vendor": Vendor;
    "state": State;
    "reason": Reason;

    /**
     * Detail 은 사람이 읽는 짧은 설명이다. 화면 분기는 Reason 으로 하고 이 값을 파싱하지 않는다.
     */
    "detail": string;

    /**
     * Plan 은 벤더가 알려준 구독 플랜 이름이다 (예: "max", "pro"). 모르면 빈 문자열이다.
     */
    "plan": string;

    /**
     * Windows 는 항상 non-nil 이다. nil 이면 JSON 에서 null 이 되어 화면이 분기해야 한다.
     */
    "windows": Window[] | null;
    "extra": ExtraAllowance;
    "observed_at": string;
}

/**
 * State 는 벤더 하나의 조회 성패다. 화면은 이 값만 보고 카드를 그릴지 안내 문구를 띄울지 정한다.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StateAvailable 은 사용 한도를 실제로 읽어 왔다는 뜻이다.
     */
    StateAvailable = "available",

    /**
     * StateUnavailable 은 이 벤더의 숫자를 지금 알 수 없다는 뜻이다. 오류가 아니라 상태다.
     */
    StateUnavailable = "unavailable",
};

/**
 * Vendor 는 로컬 파이프라인의 정식 벤더 ID를 그대로 쓴다. 별도 명명 타입을 만들지 않는다.
 */
export type Vendor = vendor$0.ID;

/**
 * Window 는 한도 창 하나다. 화면의 진행 막대 한 줄이 이 구조체 하나다.
 */
export interface Window {
    "period": PeriodKind;

    /**
     * Label 은 벤더가 그 창을 부르는 원래 이름이다 (예: "seven_day_opus", "primary").
     * 같은 PeriodKind 의 창이 둘 이상일 때 사람이 구분할 유일한 근거다.
     */
    "label": string;

    /**
     * WindowMinutes 는 창 길이(분)다. 벤더가 알려주지 않으면 0 이다.
     */
    "window_minutes": number;

    /**
     * UsedRatio 는 0.0~1.0 의 사용률이다. 벤더는 퍼센트로 주지만 화면이 매번 100 으로
     * 나누지 않도록 여기서 비율로 통일한다. 한도를 넘겨 쓴 경우 1.0 을 넘을 수 있다.
     */
    "used_ratio": number;

    /**
     * ResetsAt 은 창이 초기화되는 시각(RFC3339, UTC)이다. 모르면 빈 문자열이다.
     */
    "resets_at": string;

    /**
     * ResetsInSeconds 는 초기화까지 남은 초다. 모르면 0 이다.
     * 
     * ResetsAt 과 둘 다 두는 이유: 벤더에 따라 절대 시각만 주거나(Claude) 남은 시간만
     * 준다(Codex). 화면이 벤더마다 분기하지 않도록 어댑터가 나머지 한쪽을 파생시킨다
     * (resolveResetTimes). 파생값은 우리 시계에 의존하므로 벤더가 준 쪽을 덮어쓰지 않는다.
     */
    "resets_in_seconds": number;
}
