// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Preview {
    "installed": boolean;
    "delete_data": boolean;
    "warnings": string[] | null;
}

export interface Result {
    "success": boolean;
    "error"?: string;
    "warnings": string[] | null;
    "preserved": string[] | null;
}
