// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dashboard$0 from "../models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vendorlimit$0 from "../../vendorlimit/models.js";

export interface Monitoring {
    "state": State;
    "database_available": boolean;

    /**
     * DaemonRunning 은 runtime.json 의 pid 가 살아 있다는 뜻이다. pid 는 재사용되므로 "아마" 다.
     */
    "daemon_running": boolean;

    /**
     * DaemonStale 은 runtime.json 은 있는데 그 프로세스가 없다는 뜻이다 — 비정상 종료다.
     */
    "daemon_stale": boolean;

    /**
     * LastEventAt 은 데이터의 신선도다. 스냅샷을 만든 시각(RefreshedAt)과 다른 값이다.
     */
    "last_event_at": number;
    "running_sessions": number;
}

/**
 * Query 는 스냅샷 한 장의 조회 조건이다.
 */
export interface Query {
    /**
     * TZ 는 "오늘" 의 경계를 정한다. 빈 문자열은 UTC, 잘못된 이름은 에러다.
     */
    "tz": string;

    /**
     * RecentLimit 는 최근 세션 목록의 길이 상한이다. 0 이하는 기본값이다.
     */
    "recent_limit": number;
}

/**
 * Snapshot 은 트레이가 한 번에 받는 전부다.
 * 
 * 트레이는 창을 열지 않고 곁눈질하는 화면이라 필요한 것이 한 응답에 다 들어 있어야 한다.
 * 다섯 번 물으면 다섯 개의 실패 지점과 다섯 개의 로딩 상태가 생긴다.
 */
export interface Snapshot {
    "tz": string;
    "date": string;
    "monitoring": Monitoring;
    "active_agents": string[] | null;
    "active_sessions": number;

    /**
     * Recent 는 Home 과 같은 정의·같은 질의다. 변환 없이 그대로 싣는다 (ADR 0004).
     */
    "recent_sessions": dashboard$0.RecentSession[] | null;
    "recent_truncated": boolean;

    /**
     * Limits 는 벤더별 사용 한도다. 실패한 벤더도 unavailable 로 자리를 지킨다 —
     * 빠지면 화면이 "아직 로딩 중" 과 구분하지 못한다.
     */
    "limits": vendorlimit$0.Result[] | null;
    "limits_observed_at": string;
    "tightest_limit": TightestLimit;
}

/**
 * State 는 트레이 아이콘이 말하는 한 단어다. 값 문자열이 프런트엔드와의 계약이다.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateMonitoring = "monitoring",

    /**
     * StatePaused 는 로컬 데이터는 있는데 데몬이 돌고 있지 않다는 뜻이다.
     */
    StatePaused = "paused",

    /**
     * StateNotInstalled 는 로컬 DB 자체가 없다는 뜻이다. 오류가 아니다 (ADR 0004).
     */
    StateNotInstalled = "not_installed",
};

/**
 * TightestLimit 은 「가장 빠듯한 한도」 하나다.
 * 
 * 선택은 결정론이어야 한다 — 볼 때마다 다른 창이 강조되면 사용자는 그 표시를 믿지 않는다.
 * 순서대로: available 벤더의 창만 후보 → 사용률 높은 쪽 → 초기화 빠른 쪽(모르는 창은 맨
 * 뒤) → 벤더 이름 → 창 종류(5시간·주·월·미상) → Label → 입력 순서. 여기까지가 전순서다.
 */
export interface TightestLimit {
    /**
     * Found 가 false 면 후보가 하나도 없었다는 뜻이다. 나머지 필드는 영값이다.
     */
    "found": boolean;
    "vendor": string;
    "period": vendorlimit$0.PeriodKind;
    "label": string;

    /**
     * UsedRatio 는 0.0~1.0 사용률이다. 한도를 넘겨 쓴 경우 1.0 을 넘을 수 있다.
     */
    "used_ratio": number;

    /**
     * ResetsAt 은 RFC3339 UTC 다. 모르면 빈 문자열, ResetsInSeconds 는 0 이다.
     */
    "resets_at": string;
    "resets_in_seconds": number;
}
