// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dashboard$0 from "../dashboard/models.js";

/**
 * ActivityDetail은 같은 세션 ID로 조회한 상세·지표·분류를 묶는다.
 */
export interface ActivityDetail {
    "detail": dashboard$0.SessionDetail;
    "metrics": dashboard$0.SessionMetrics;
    "classification": dashboard$0.SessionClassification;
}
