// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pricing$0 from "../pricing/models.js";

/**
 * CostSummary 는 구간(또는 세션) 하나의 예상 비용이다.
 * 
 * 금액 필드가 Total 하나뿐인 것은 pricing.Cost 와 같은 이유다 — 보고값과 추정값을 서로
 * 다른 필드에 담아 두면 언젠가 누군가 둘 다 더한다. 어느 쪽이 몇 건이었는지는 아래 개수가
 * 말한다.
 */
export interface CostSummary {
    /**
     * Total 은 이 구간의 비용이다. 정수 nano-USD 로 더한 값이라 더하는 순서에 무관하다.
     */
    "total": pricing$0.Money;

    /**
     * Calls 는 이 구간의 LLM 호출 수다. Reported+Estimated+Unavailable 과 같다.
     */
    "calls": number;

    /**
     * Reported 는 벤더가 보고한 cost_usd 를 그대로 쓴 호출 수다.
     */
    "reported": number;

    /**
     * Estimated 는 보고값이 없어 토큰 단가로 계산한 호출 수다.
     */
    "estimated": number;

    /**
     * Unavailable 은 비용을 정하지 못한 호출 수다. **Total 에 0 원으로 들어간 것이 아니라
     * 빠져 있다.** 이 값이 크면 화면은 "일부 호출의 비용을 알 수 없음" 을 알려야 한다.
     */
    "unavailable": number;

    /**
     * CacheSavings 는 캐시로 아낀(음수면 더 낸) 금액이다. **Total 과 더하지 않는다** —
     * 비용이 아니라 반사실(counterfactual)이다 (internal/pricing/savings.go).
     */
    "cache_savings": pricing$0.Money;

    /**
     * TableVersion·EffectiveDate 는 이 값을 만든 가격표의 판이다. 화면에 뜬 비용이 어느
     * 판의 단가에서 나왔는지 되짚을 수 있어야 한다.
     */
    "table_version": string;
    "effective_date": string;
}

/**
 * RecentSession 은 최근 활동 목록의 한 줄이다 — 화면 표시용 요약이다.
 * 
 * SessionRow 를 그대로 쓰지 않는 이유는 두 가지다. 목록이 쓰지 않는 20여 개 필드를 매 행
 * 상관 서브쿼리로 다시 세지 않아도 되고, 비용을 가격표 기준으로 낼 수 있다 —
 * SessionRow.CostUSD 는 보고값 합이다. 자세한 지표는 Session(id) 가 준다.
 */
export interface RecentSession {
    /**
     * ID 는 sessions.id 다. Session(id) 의 인자이자 화면 이동의 키다.
     */
    "id": number;

    /**
     * SessionKey 는 벤더가 준 세션 식별자다. 표시·디버깅용이다.
     */
    "session_key": string;
    "vendor": string;
    "title": string;

    /**
     * WorkspacePath 는 작업 폴더 원경로, ProjectName 은 그 basename 이다 (ADR 0010).
     */
    "workspace_path": string;
    "project_name": string;
    "started_at": number;

    /**
     * LastEventAt 은 마지막으로 알려진 활동 시각이다 (sessions.go 의 lastActivityExpr).
     */
    "last_event_at": number;

    /**
     * EndedAt 이 null 이면 진행 중이다. Status 가 그것을 문자열로 말한다.
     */
    "ended_at": number | null;
    "status": string;
    "duration_ms": number;
    "active_seconds": number;
    "input_tokens": number;
    "output_tokens": number;

    /**
     * Tokens 는 입력+출력이다. reasoning 은 출력의 부분집합이고 캐시는 더하지 않는다.
     */
    "tokens": number;

    /**
     * Cost 는 이 세션 **생애 전체**의 예상 비용이다. 선택 날짜로 자른 값이 아니다
     * (Home 머리말의 「합계의 정의」).
     */
    "cost": CostSummary;
}
