// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pricing$0 from "../pricing/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vendorlimit$0 from "../vendorlimit/models.js";

/**
 * CostSummary 는 구간(또는 세션) 하나의 예상 비용이다.
 * 
 * 금액 필드가 Total 하나뿐인 것은 pricing.Cost 와 같은 이유다 — 보고값과 추정값을 서로
 * 다른 필드에 담아 두면 언젠가 누군가 둘 다 더한다. 어느 쪽이 몇 건이었는지는 아래 개수가
 * 말한다.
 */
export interface CostSummary {
    /**
     * Total 은 이 구간의 비용이다. 정수 nano-USD 로 더한 값이라 더하는 순서에 무관하다.
     */
    "total": pricing$0.Money;

    /**
     * Calls 는 이 구간의 LLM 호출 수다. Reported+Estimated+Unavailable 과 같다.
     */
    "calls": number;

    /**
     * Reported 는 벤더가 보고한 cost_usd 를 그대로 쓴 호출 수다.
     */
    "reported": number;

    /**
     * Estimated 는 보고값이 없어 토큰 단가로 계산한 호출 수다.
     */
    "estimated": number;

    /**
     * Unavailable 은 비용을 정하지 못한 호출 수다. **Total 에 0 원으로 들어간 것이 아니라
     * 빠져 있다.** 이 값이 크면 화면은 "일부 호출의 비용을 알 수 없음" 을 알려야 한다.
     */
    "unavailable": number;

    /**
     * CacheSavings 는 캐시로 아낀(음수면 더 낸) 금액이다. **Total 과 더하지 않는다** —
     * 비용이 아니라 반사실(counterfactual)이다 (internal/pricing/savings.go).
     */
    "cache_savings": pricing$0.Money;

    /**
     * TableVersion·EffectiveDate 는 이 값을 만든 가격표의 판이다. 화면에 뜬 비용이 어느
     * 판의 단가에서 나왔는지 되짚을 수 있어야 한다.
     */
    "table_version": string;
    "effective_date": string;
}

/**
 * RecentSession 은 최근 활동 목록의 한 줄이다 — 화면 표시용 요약이다.
 * 
 * SessionRow 를 그대로 쓰지 않는 이유는 두 가지다. 목록이 쓰지 않는 20여 개 필드를 매 행
 * 상관 서브쿼리로 다시 세지 않아도 되고, 비용을 가격표 기준으로 낼 수 있다 —
 * SessionRow.CostUSD 는 보고값 합이다. 자세한 지표는 Session(id) 가 준다.
 */
export interface RecentSession {
    /**
     * ID 는 sessions.id 다. Session(id) 의 인자이자 화면 이동의 키다.
     */
    "id": number;

    /**
     * SessionKey 는 벤더가 준 세션 식별자다. 표시·디버깅용이다.
     */
    "session_key": string;
    "vendor": string;
    "title": string;

    /**
     * WorkspacePath 는 작업 폴더 원경로, ProjectName 은 그 basename 이다 (ADR 0010).
     */
    "workspace_path": string;
    "project_name": string;
    "started_at": number;

    /**
     * LastEventAt 은 마지막으로 알려진 활동 시각이다 (sessions.go 의 lastActivityExpr).
     */
    "last_event_at": number;

    /**
     * EndedAt 이 null 이면 진행 중이다. Status 가 그것을 문자열로 말한다.
     */
    "ended_at": number | null;
    "status": string;
    "duration_ms": number;
    "active_seconds": number;
    "input_tokens": number;
    "output_tokens": number;

    /**
     * Tokens 는 입력+출력이다. reasoning 은 출력의 부분집합이고 캐시는 더하지 않는다.
     */
    "tokens": number;

    /**
     * Cost 는 이 세션 **생애 전체**의 예상 비용이다. 선택 날짜로 자른 값이 아니다
     * (Home 머리말의 「합계의 정의」).
     */
    "cost": CostSummary;
}

/**
 * TightestLimit 은 「가장 빠듯한 한도」 하나다.
 * 
 * # 선택 규칙 — 결정론이어야 한다
 * 
 * 같은 입력에 늘 같은 답을 내야 한다. 그러지 않으면 트레이를 볼 때마다 다른 창이 강조되고
 * 사용자는 그 표시를 믿지 않게 된다. 순서대로 다음을 본다.
 * 
 *  1. **후보**: State 가 available 인 벤더의 창만. unavailable 벤더는 숫자 자체가 없으므로
 *     이길 수도, 다른 벤더의 선택을 흔들 수도 없다.
 *  2. **사용률이 높은 쪽**이 이긴다 (UsedRatio 내림차순). "빠듯하다" 의 1차 정의다.
 *  3. 사용률이 같으면 **초기화가 빠른 쪽**이 이긴다 (ResetsInSeconds 오름차순).
 *     같은 90% 라도 5분 뒤 풀리는 창보다 6일 뒤 풀리는 창이 더 아프다.
 *     초기화 시각을 **모르는 창**(ResetsInSeconds == 0)은 아는 창보다 항상 뒤로 간다 —
 *     0 을 "0초 뒤" 로 읽으면 정보가 없는 창이 늘 이겨 버린다.
 *  4. 그래도 같으면 **벤더 이름 오름차순** → **창 종류**(5시간 → 주 → 월 → 미상) →
 *     **Label 오름차순** → **입력 순서**. 여기까지 오면 전순서라 결과가 하나로 확정된다.
 */
export interface TightestLimit {
    /**
     * Found 가 false 면 후보가 하나도 없었다는 뜻이다. 나머지 필드는 영값이다.
     */
    "found": boolean;
    "vendor": string;
    "period": vendorlimit$0.PeriodKind;
    "label": string;

    /**
     * UsedRatio 는 0.0~1.0 사용률이다. 한도를 넘겨 쓴 경우 1.0 을 넘을 수 있다.
     */
    "used_ratio": number;

    /**
     * ResetsAt 은 RFC3339 UTC 다. 모르면 빈 문자열, ResetsInSeconds 는 0 이다.
     */
    "resets_at": string;
    "resets_in_seconds": number;
}

/**
 * TrayMonitoring 은 트레이가 그리는 모니터링 상태다.
 */
export interface TrayMonitoring {
    "state": TrayState;

    /**
     * DatabaseAvailable 은 로컬 DB 를 열었다는 뜻이다.
     */
    "database_available": boolean;

    /**
     * DaemonRunning 은 runtime.json 의 pid 가 살아 있다는 뜻이다. pid 는 재사용되므로
     * 이 값은 "아마" 다 (Status.Daemon 주석).
     */
    "daemon_running": boolean;

    /**
     * DaemonStale 은 runtime.json 은 있는데 그 프로세스가 없다는 뜻이다 — 비정상 종료다.
     */
    "daemon_stale": boolean;

    /**
     * LastEventAt 은 마지막으로 수집된 이벤트 시각(UTC unix 초)이다. 0 이면 아직 없음.
     * **데이터의 신선도**이고, 스냅샷을 만든 시각(RefreshedAt)과 다른 값이다.
     */
    "last_event_at": number;

    /**
     * RunningSessions 는 지금 진행 중인(ended_at IS NULL) 세션 수다.
     */
    "running_sessions": number;
}

/**
 * TrayQuery 는 스냅샷 한 장의 조회 조건이다.
 */
export interface TrayQuery {
    /**
     * TZ 는 "오늘" 의 경계를 정하는 시간대다. 빈 문자열은 UTC, 잘못된 이름은 에러다.
     */
    "tz": string;

    /**
     * RecentLimit 는 최근 세션 목록의 길이 상한이다. 0 이하는 기본값이다.
     */
    "recent_limit": number;
}

/**
 * TraySnapshot 은 트레이가 한 번에 받는 전부다.
 */
export interface TraySnapshot {
    "tz": string;

    /**
     * Date 는 TZ 기준 스냅샷이 다루는 날짜다.
     */
    "date": string;
    "monitoring": TrayMonitoring;

    /**
     * RefreshedAt 은 **마지막으로 성공한** 갱신 시각(UTC unix 초)이다. 화면의
     * "몇 분 전 기준" 이 이것을 쓴다.
     */
    "refreshed_at": number;

    /**
     * CheckedAt 은 마지막 **시도** 시각이다. 갱신이 실패하면 RefreshedAt 은 그대로이고
     * 이 값만 움직인다.
     */
    "checked_at": number;

    /**
     * Stale 은 마지막 시도가 실패해 여기 담긴 값이 RefreshedAt 시점의 것이라는 뜻이다.
     */
    "stale": boolean;

    /**
     * StaleReason 은 Stale 의 기계 판독 가능한 원인이다. Stale 이 false 면 빈 문자열이다.
     */
    "stale_reason": string;

    /**
     * ActiveAgents·ActiveSessions 는 지금 진행 중인 세션의 벤더와 수다.
     */
    "active_agents": string[] | null;
    "active_sessions": number;

    /**
     * Recent 는 오늘 시작한 세션의 요약이다 (Home 과 같은 정의·같은 질의).
     */
    "recent_sessions": RecentSession[] | null;

    /**
     * RecentTruncated 가 true 면 목록이 RecentLimit 에서 잘렸다.
     */
    "recent_truncated": boolean;

    /**
     * Limits 는 벤더별 사용 한도다. **실패한 벤더도 unavailable 로 자리를 지킨다** —
     * 빠지면 화면이 "아직 로딩 중" 과 구분하지 못한다 (vendorlimit.Snapshot).
     */
    "limits": vendorlimit$0.Result[] | null;

    /**
     * LimitsObservedAt 은 한도를 관측한 시각(RFC3339 UTC)이다.
     */
    "limits_observed_at": string;

    /**
     * Tightest 는 available 한 창들 중 가장 빠듯한 하나다.
     */
    "tightest_limit": TightestLimit;
}

/**
 * TrayState 는 트레이 아이콘이 말하는 한 단어다. 값 문자열이 프런트엔드와의 계약이다.
 */
export enum TrayState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * TrayStateMonitoring 은 데몬이 살아 있어 지금도 수집하고 있다는 뜻이다.
     */
    TrayStateMonitoring = "monitoring",

    /**
     * TrayStatePaused 는 로컬 데이터는 있는데 데몬이 돌고 있지 않다는 뜻이다.
     * 과거 데이터는 그대로 보이지만 새 활동은 들어오지 않는다.
     */
    TrayStatePaused = "paused",

    /**
     * TrayStateNotInstalled 는 로컬 DB 자체가 없다는 뜻이다 — 미설치이거나 로컬
     * 파이프라인을 켠 적이 없다. 오류가 아니다 (ADR 0004).
     */
    TrayStateNotInstalled = "not_installed",
};
