// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dashboard$0 from "../models.js";

/**
 * Query는 현지 날짜 양 끝을 포함하는 홈 조회다. 최대 400일을 받는다.
 */
export interface Query {
    "tz": string;
    "start": string;
    "end": string;
}

/**
 * Snapshot은 홈 한 장이다. 사용량은 사실 발생 시각, 세션 목록은 시작 시각으로 자른다.
 * 목록 각 행의 토큰·비용은 세션 생애 전체다. 활동 시간도 시작일에 통째로 귀속된다.
 */
export interface Snapshot {
    "usage": dashboard$0.HomeBreakdown;
    "end_date": string;
    "unit": string;
    "bucket_size": number;
    "recent": dashboard$0.RecentSession[] | null;
    "recent_truncated": boolean;
    "running_sessions": number;

    /**
     * ActiveAgents는 현재 진행 중인 벤더다. 헤더는 선택 기간과 무관하게 사용한다.
     */
    "active_agents": string[] | null;
    "database_available": boolean;
}
