// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Money 는 금액 하나다. NanoUSD 가 원본이고 USD 는 화면용 파생값이다.
 * 
 * 둘을 함께 내보내는 이유는 소비자가 둘로 갈리기 때문이다 — GUI 는 USD 만 쓰고,
 * 여러 호출을 합산하는 쪽(Today 카드·세션 합계)은 NanoUSD 를 정수로 더해야 오차가 없다.
 * **합산은 반드시 NanoUSD 로 한다.**
 */
export interface Money {
    "nano_usd": NanoUSD;
    "usd": number;
}

/**
 * NanoUSD 는 10억분의 1 USD 단위의 정수 금액이다. int64 의 범위는 약 92 억 USD 로,
 * 이 도구가 다루는 개인·팀 단위 비용에 비하면 사실상 무한하다.
 */
export type NanoUSD = number;
